#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#
name: Build GSWIFI PSG1218

on:
  workflow_dispatch:

env:
  CONFIG_FILE: config
  DIY_P2_SH: diy-part2.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Install dependencies
        run: |
          sudo timedatectl set-timezone "$TZ"
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
          gettext git java-propose-classpath libncurses5-dev libssl-dev \
          python3 python3-distutils unzip wget subversion mercurial

      
      - name: Update and install feeds
        run: |
          chmod +x ${{ env.DIY_P2_SH }}
          ./${{ env.DIY_P2_SH }}

     
      - name: Apply custom config
        run: |
          cp ${{ env.CONFIG_FILE }} .config
          make defconfig

      
      - name: Get device name
        id: device
        run: |
          DEVICE_NAME=$(grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/')
          echo "DEVICE_NAME=$DEVICE_NAME" >> $GITHUB_ENV
          FILE_DATE=$(date +"%Y%m%d%H%M")
          echo "FILE_DATE=$FILE_DATE" >> $GITHUB_ENV

      
      - name: Compile firmware
        run: |
          echo "Start compiling PSG1218 firmware using $(nproc) cores"
          make -j$(nproc) V=s

      
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: GSWIFI-${{ env.DEVICE_NAME }}-${{ env.FILE_DATE }}
          path: bin/targets/ramips/mt7620/
