name: Build GSWIFI PSG1218

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
          gettext git java-propose-classpath libncurses5-dev libssl-dev \
          python3 python3-distutils unzip wget subversion mercurial

      - name: Apply config and DIY scripts
        run: |
          cp config .config
          chmod +x diy-part2.sh
          ./diy-part2.sh

      - name: Build firmware
        run: |
          make defconfig
          make -j$(nproc) V=s

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: GSWIFI-PSG1218
          path: bin/targets/ramips/mt7620/
